
events {
    worker_connections 1024;  # Maximum number of simultaneous connections per worker
}

http {
    server {
        listen 80;
        server_name localhost;

        # Redirect HTTP to HTTPS (optional)
        location / {
            proxy_pass http://go_gateway:8080;  # Forward requests to the Go reverse proxy
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/ssl/certs/waf.crt;  # Path to your SSL certificate
        ssl_certificate_key /etc/ssl/private/waf.key;  # Path to your SSL key

        # SSL settings with more common ciphers
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384';
        ssl_prefer_server_ciphers on;

        location / {
            proxy_pass http://go_gateway:8080;  # Forward requests to the Go reverse proxy
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
